### 회원가입
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "loginId": "user01",
  "password": "Password1!",
  "name": "홍길동",
  "birthDate": "1990-01-01",
  "email": "user@example.com"
}

---

### 내 정보 조회
GET http://localhost:8080/api/v1/users/me
X-Loopers-LoginId: user01
X-Loopers-LoginPw: Password1!

---

### 비밀번호 변경
PUT http://localhost:8080/api/v1/users/password
Content-Type: application/json
X-Loopers-LoginId: user01
X-Loopers-LoginPw: Password1!

{
  "oldPassword": "Password1!",
  "newPassword": "NewPassword1!"
}

---

### 회원 탈퇴
DELETE http://localhost:8080/api/v1/users/me
X-Loopers-LoginId: user01
X-Loopers-LoginPw: Password1!
